#requires -Version 7.0
[CmdletBinding()]
param(
    [ValidateSet('Preview', 'Apply', 'Verify')]
    [string]$Stage = 'Preview',
    [ValidatePattern('^[a-z][a-z0-9-]{2,47}$')]
    [string]$AgentName,
    [switch]$FromAzdHook,
    [ValidatePattern('^https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+(?:\.git)?$')]
    [string]$GitHubRepositoryUrl,
    [switch]$EnableGitHubIssues,
    [switch]$EnableEmail
)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false
$lab = Split-Path $PSScriptRoot -Parent
$workload = Join-Path $lab 'ticketingapp-source'
$repo = [IO.Path]::GetFullPath((Join-Path $lab '..\..'))

function Read-EnvironmentValue([string]$Name, [switch]$Optional) {
    $value = & azd -C $workload env get-value $Name 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace(($value -join ''))) {
        if ($Optional) { return '' }
        throw "Missing $Name in the selected azd environment. Complete workload deployment first."
    }
    return ($value -join '').Trim()
}

function Invoke-LabScript([string]$Path, [hashtable]$Parameters) {
    $global:LASTEXITCODE = 0
    & $Path @Parameters
    if ($LASTEXITCODE -ne 0) { throw "Stage failed: $Path (exit $LASTEXITCODE). Inspect the failure before retrying." }
}

if ($FromAzdHook) {
    $optIn = Read-EnvironmentValue ONBOARDING_CONFIGURE_AGENT -Optional
    if ($optIn -ne 'true') {
        Write-Host 'Workload deployed. Agent setup was not selected. Follow docs/setup.md to configure the agent.'
        $global:LASTEXITCODE = 0
        return
    }
    $Stage = 'Apply'
}
if (-not $AgentName) { $AgentName = Read-EnvironmentValue ONBOARDING_AGENT_NAME -Optional }
if ($AgentName -notmatch '^[a-z][a-z0-9-]{2,47}$') {
    throw 'Set ONBOARDING_AGENT_NAME to a unique lowercase name (3-48 characters), or pass -AgentName.'
}
$subscription = Read-EnvironmentValue AZURE_SUBSCRIPTION_ID
$resourceGroup = Read-EnvironmentValue AZURE_RESOURCE_GROUP
$location = Read-EnvironmentValue AZURE_LOCATION
$environmentName = Read-EnvironmentValue AZURE_ENV_NAME
if ($environmentName -notmatch '^[A-Za-z0-9_-]+$') { throw 'Unsafe azd environment name.' }
$config = Join-Path $workload ".azure\$environmentName\$AgentName"
$agentId = "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.App/agents/$AgentName"
$portal = "https://sre.azure.com/agents$agentId"
$selectionPath = Join-Path $config 'onboarding-selection.json'
$selection = @{ agentName = $AgentName; subscription = $subscription; resourceGroup = $resourceGroup; location = $location; githubRepository = "$GitHubRepositoryUrl"; githubIssues = [bool]$EnableGitHubIssues; email = [bool]$EnableEmail }
if ($EnableGitHubIssues -and -not $GitHubRepositoryUrl) { throw '-EnableGitHubIssues requires -GitHubRepositoryUrl.' }

if (-not (Test-Path -LiteralPath $selectionPath)) {
    if (Test-Path -LiteralPath $config) {
        throw "Existing configuration at $config was not generated by this helper. Inspect it; no files were overwritten."
    }
    if ($Stage -eq 'Verify') { throw "Configuration not found at $config. Run the Preview stage first." }
    Invoke-LabScript (Join-Path $repo 'sreagent-templates\bin\ps\New-Agent.ps1') @{
        RecipePath = (Join-Path $lab 'agent-recipe')
        Subscription = $subscription
        Set = @{
            agentName = $AgentName
            resourceGroup = $resourceGroup
            location = $location
            appInsightsId = (Read-EnvironmentValue APPLICATION_INSIGHTS_ID)
            appInsightsAppId = (Read-EnvironmentValue APPLICATION_INSIGHTS_APP_ID)
            modelProvider = 'Anthropic'
        }
        Output = $config
        NonInteractive = $true
        NoTelemetry = $true
    }
    $expected = Get-Content (Join-Path $config 'expected-config.json') -Raw | ConvertFrom-Json -AsHashtable
    $policyPath = Join-Path $config 'tool-permissions.json'
    $policy = Get-Content $policyPath -Raw | ConvertFrom-Json -AsHashtable
    if ($GitHubRepositoryUrl) {
        $repoConfig = Join-Path $config 'config\repos'
        $null = New-Item -ItemType Directory -Path $repoConfig -Force
        @{
            name = 'ticketingapp-source'
            spec = @{ url = $GitHubRepositoryUrl; branch = 'main'; description = 'Selected lab source repository' }
        } | ConvertTo-Json -Depth 8 | Set-Content (Join-Path $repoConfig 'ticketingapp-source.yaml') -Encoding utf8
        $expected.repos = @('ticketingapp-source')
        $expected.repoBranches = @{ 'ticketingapp-source' = 'main' }
    }
    if ($EnableGitHubIssues) {
        $policy.allow += @('FetchGithubIssue', 'FetchGithubIssues')
        $policy.ask += 'CreateGithubIssue'
    }
    if ($EnableEmail) {
        $connectionDir = Join-Path $config 'config\connectorv2'
        $null = New-Item -ItemType Directory -Path $connectionDir -Force
        Copy-Item -LiteralPath (Join-Path $lab 'agent-recipe\optional\connectorv2\outlook.yaml') -Destination $connectionDir
        $expected.managedConnectors = @('office365')
        $policy.allow += 'ListOutlookEmails'
        $policy.ask += 'SendOutlookEmail'
    }
    $expected.toolPermissions = $policy
    $policy | ConvertTo-Json -Depth 10 | Set-Content $policyPath -Encoding utf8
    $expected | ConvertTo-Json -Depth 30 | Set-Content (Join-Path $config 'expected-config.json') -Encoding utf8
    $selection | ConvertTo-Json | Set-Content $selectionPath -Encoding utf8
}
else {
    $savedSelection = Get-Content $selectionPath -Raw | ConvertFrom-Json -AsHashtable
    foreach ($key in $selection.Keys) {
        if ($savedSelection[$key] -cne $selection[$key]) {
            throw "Setup selection changed ($key). Review the existing configuration at $config; no changes were applied."
        }
    }
}

Write-Host "Target: $agentId"
Write-Host "Configuration: $config"
Write-Host "Stage: $Stage"
if ($Stage -eq 'Preview') {
    Invoke-LabScript (Join-Path $repo 'sreagent-templates\bicep\Assemble-Agent.ps1') @{
        ConfigDir = $config
        Output = (Join-Path $config 'preview')
    }
    Write-Host 'No Azure changes were applied. Review generated configuration and cost/access boundaries, then explicitly run -Stage Apply.'
    return
}

$verify = Join-Path $repo 'sreagent-templates\bin\ps\Verify-Agent.ps1'
$verifyArgs = @{ SubscriptionId = $subscription; ResourceGroup = $resourceGroup; AgentName = $AgentName; Expected = $config }
if ($Stage -eq 'Apply') {
    $agentsRaw = & az resource list --subscription $subscription --resource-group $resourceGroup --resource-type Microsoft.App/agents --output json --only-show-errors
    if ($LASTEXITCODE -ne 0) { throw 'Could not inspect existing agents; no deployment attempted.' }
    $existing = @($agentsRaw | ConvertFrom-Json | Where-Object name -eq $AgentName)
    if ($existing.Count) {
        Write-Host 'Existing agent: verifying before touching configuration. Missing components or drift require explicit operator review.'
        Invoke-LabScript $verify $verifyArgs
        Write-Host 'Base configuration verified. Existing workflow and learner objects were preserved; use the workflow installer only after reviewing its changes.'
    }
    else {
        Invoke-LabScript (Join-Path $repo 'sreagent-templates\bin\ps\Deploy-Agent.ps1') @{
            InputPath = $config
            DeploymentName = "$AgentName-deployment"
            Subscription = $subscription
            NoTelemetry = $true
        }
        Invoke-LabScript (Join-Path $PSScriptRoot 'install-workflow-template.ps1') @{
            Subscription = $subscription
            AgentName = $AgentName
            Template = (Join-Path $lab 'workflow-templates\incidentinvestigation-workflowtemplate.yaml')
        }
        if ($GitHubRepositoryUrl -or $EnableEmail) {
            Write-Host 'Core workflow installed. Optional workflow tools require the separately approved installer flags after completing the selected consent.'
        }
    }
    foreach ($entry in @{ SRE_AGENT_NAME = $AgentName; SRE_AGENT_RESOURCE_ID = $agentId; SRE_AGENT_URL = $portal }.GetEnumerator()) {
        & azd -C $workload env set $entry.Key $entry.Value
        if ($LASTEXITCODE -ne 0) { throw "Could not save azd output $($entry.Key)." }
    }
}
Invoke-LabScript $verify $verifyArgs
Write-Host "Agent: $portal"
Write-Host 'Base configuration verified. Check the incident workflow separately. Checkout, telemetry, skill reuse and a scheduled run still require the learner checkpoints.'
